version: '3.8'

services:

  rabbitmq:
    image: 'rabbitmq:management-alpine'
    ports:
      - '5672:5672' # AMQP
      - '15672:15672' # Management UI
    networks:
      - coin_commerce_network
  
networks:
  coin_commerce_network:
    driver: bridge